name: Rust

on:
  release:
    types: [created]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # cache the build assets so they dont recompile every time.
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Install system dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y \
          libgtk-3-dev
      - name: Build & Package
        run: cargo build --all --release && mv target/release/pkbv_rs  target/release/pkbv-rs && zip ${{ runner.OS }}.zip target/release/pkbv-rs move sprites

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.OS }}.zip

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build & Package
        run: cargo build --all --release && mv target/release/pkbv_rs target/release/pkbv-rs && 7z a -tzip ${{ runner.OS }}.zip target/release/pkbv-rs move sprites

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.OS }}.zip

  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Rust dependencies
        uses: actions/cache@v1.0.1
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          default: true
          override: true

      - name: Build & Package
        run: cargo build --all --release && mv target/release/pkbv_rs.exe target/release/pkbv-rs.exe && 7z a -tzip ${{ runner.OS }}.zip target/release/pkbv-rs.exe move sprites

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ runner.OS }}.zip